# Build and deploy API documentation to GitHub Pages

name: Document

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & deploy docs
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Generate documentation
        run: |
          RUSTDOCFLAGS="--cfg docsrs" \
            cargo doc --no-deps --all-features --workspace

      - name: Create index redirect
        run: echo '<html><head><meta http-equiv="refresh" content="0; url=/qrc/"></head><body></body></html>' > ./target/doc/index.html

      - name: Write CNAME file
        run: echo 'doc.qrclib.one' > ./target/doc/CNAME

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: documentation
          path: target/doc
          if-no-files-found: error
          retention-days: 1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          cname: true
          commit_message: Deploy documentation at ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          user_email: actions@users.noreply.github.com
          user_name: github-actions
